/**
 * Root Layout Component
 * Rewrite with TypeScript on 2026/3/10 (1773140135)
 *
 * Defines the root HTML structure and provides global context providers
 * for the entire application. This layout wraps all pages and includes
 * essential providers for authentication and competition state management.
 *
 * @component
 * @param {Object} props - Component properties
 * @param {React.ReactNode} props.children - Child pages/components to render
 * @returns {JSX.Element} Root HTML structure with providers
 */

"use client"

import React, { ReactNode } from "react"
import "./globals.css"
import Navbar from "@/src/components/Navbar"
import Footer from "@/src/components/Footer"
import { SessionProvider } from "next-auth/react"
import { CompetitionProvider } from "@/src/context/CompetitionContext"

// Note: Font imports commented out but available for future use
// import { Geist, Geist_Mono } from "next/font/google";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

/**
 * Props for the RootLayout component
 */
interface RootLayoutProps {
    /** Child pages/components to render */
    children: ReactNode
}

// Note: Metadata cannot be exported from a client component
// If you need metadata, move it to a separate server component or use a layout.tsx without "use client"
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

/**
 * Root Layout Component
 * 
 * Provides the base HTML structure and context providers for the entire application.
 * 
 * @param {RootLayoutProps} props - Component props
 * @returns {JSX.Element} Root layout with providers
 */
export default function RootLayout({ children }: RootLayoutProps): React.ReactElement {
    return (
        <html lang="en">
            <head>
                {/* Prevent search engine indexing for development/competition sites */}
                <meta name="robots" content="noindex, nofollow" />

                {/* Responsive viewport configuration */}
                <meta name="viewport" content="width=device-width, initial-scale=1" />

                {/* Application title */}
                <title>Network Hackathon Site</title>
            </head>
            <body>
                {/* NextAuth Session Provider for authentication state management */}
                <SessionProvider>
                    <div className="biggestWrap">
                        {/* Global navigation bar */}
                        <Navbar />

                        {/* Main content wrapper with competition state provider */}
                        <div className="bigWrap">
                            <CompetitionProvider>{children}</CompetitionProvider>
                        </div>

                        {/* Global footer */}
                        <Footer />
                    </div>
                </SessionProvider>
            </body>
        </html>
    )
}